version: '3.4'
services:
  haproxy:
    image: haproxy:alpine
    container_name: haproxy
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg      
      - ./docker/haproxy/data/ssl:/usr/local/etc/haproxy/ssl
  nginx:
    image: nginx:alpine
    container_name: project1_example
    ports:
      - 8080:80